// GENERATED by Tools/slice_decor.py — do not edit by hand; change the script and run it again.
using System.Collections.Generic;
using UnityEngine;

namespace LQFarm
{
    /// <summary>The painted yard props cut from the owner's decor sheets (Resources/Art/decor), measured by
    /// Tools/slice_decor.py: where each one touches the ground, how wide its footprint is, and where its
    /// lanterns and fires are. IslandView.Places says which island stands what where.</summary>
    public static class DecorCatalog
    {
        public struct Light { public Vector2 at; public bool fire; }

        public struct Entry
        {
            /// <summary>Height of the footprint's centre above the sprite's bottom edge, 0..1 of its height.</summary>
            public float pivotY;
            /// <summary>Footprint width as a share of the sprite's width.</summary>
            public float footW;
            /// <summary>Aspect: height / width.</summary>
            public float aspect;
            /// <summary>Lantern flames and fires, normalised (0,0 bottom-left .. 1,1 top-right).</summary>
            public Light[] lights;
            /// <summary>Grounds this prop has a recoloured skirt for (snow, ash, slate, sand, ice).</summary>
            public string[] grounds;
            /// <summary>Painted standing on a grass skirt (false: it stands on nothing and has a contact shadow).</summary>
            public bool skirt;
            /// <summary>A part lifted off to turn (the windmill's sails, Art/decor/<name>_sails): its hub, normalised like
            /// the lights, and its square's side as a share of the sprite's width. spinSize 0: nothing turns.</summary>
            public Vector2 spinAt;
            public float spinSize;
        }

        public static readonly Dictionary<string, Entry> All = new Dictionary<string, Entry>
        {
            { "flower_barrow", new Entry { pivotY = 0.216f, footW = 0.581f, aspect = 0.705f, skirt = false, lights = new Light[] {  }, grounds = new string[] {  } } },
            { "water_tub", new Entry { pivotY = 0.182f, footW = 0.631f, aspect = 0.932f, skirt = false, lights = new Light[] { new Light { at = new Vector2(0.891f, 0.628f), fire = false } }, grounds = new string[] {  } } },
            { "campfire", new Entry { pivotY = 0.226f, footW = 0.953f, aspect = 1.112f, skirt = false, lights = new Light[] { new Light { at = new Vector2(0.846f, 0.577f), fire = false }, new Light { at = new Vector2(0.493f, 0.277f), fire = true } }, grounds = new string[] {  } } },
            { "watering_can", new Entry { pivotY = 0.176f, footW = 0.414f, aspect = 0.646f, skirt = false, lights = new Light[] {  }, grounds = new string[] {  } } },
            { "pumpkin_crate", new Entry { pivotY = 0.228f, footW = 0.653f, aspect = 0.760f, skirt = false, lights = new Light[] {  }, grounds = new string[] {  } } },
            { "bird_bath_g", new Entry { pivotY = 0.200f, footW = 0.979f, aspect = 1.134f, skirt = true, lights = new Light[] {  }, grounds = new string[] {  } } },
            { "lily_pond", new Entry { pivotY = 0.291f, footW = 0.910f, aspect = 0.706f, skirt = true, lights = new Light[] {  }, grounds = new string[] {  } } },
            { "rock_lamp", new Entry { pivotY = 0.255f, footW = 0.991f, aspect = 0.885f, skirt = true, lights = new Light[] { new Light { at = new Vector2(0.712f, 0.669f), fire = false } }, grounds = new string[] { "slate" } } },
            { "stump_shrooms", new Entry { pivotY = 0.289f, footW = 0.953f, aspect = 0.742f, skirt = true, lights = new Light[] {  }, grounds = new string[] {  } } },
            { "sunflower_fence", new Entry { pivotY = 0.328f, footW = 0.918f, aspect = 0.641f, skirt = true, lights = new Light[] {  }, grounds = new string[] {  } } },
            { "birdhouse_post", new Entry { pivotY = 0.102f, footW = 0.643f, aspect = 1.433f, skirt = true, lights = new Light[] {  }, grounds = new string[] {  } } },
            { "crystals", new Entry { pivotY = 0.258f, footW = 0.932f, aspect = 0.813f, skirt = true, lights = new Light[] {  }, grounds = new string[] { "slate", "ice" } } },
            { "blueberry", new Entry { pivotY = 0.214f, footW = 0.869f, aspect = 0.944f, skirt = true, lights = new Light[] {  }, grounds = new string[] {  } } },
            { "berry_basket", new Entry { pivotY = 0.218f, footW = 0.881f, aspect = 0.938f, skirt = true, lights = new Light[] {  }, grounds = new string[] {  } } },
            { "giant_shroom", new Entry { pivotY = 0.228f, footW = 0.943f, aspect = 0.948f, skirt = true, lights = new Light[] {  }, grounds = new string[] {  } } },
            { "glow_pod", new Entry { pivotY = 0.182f, footW = 0.914f, aspect = 1.167f, skirt = true, lights = new Light[] { new Light { at = new Vector2(0.503f, 0.396f), fire = true } }, grounds = new string[] {  } } },
            { "veg_cart", new Entry { pivotY = 0.302f, footW = 0.972f, aspect = 0.734f, skirt = true, lights = new Light[] {  }, grounds = new string[] { "sand" } } },
            { "clay_oven", new Entry { pivotY = 0.247f, footW = 0.977f, aspect = 0.907f, skirt = true, lights = new Light[] { new Light { at = new Vector2(0.565f, 0.234f), fire = true } }, grounds = new string[] { "ash" } } },
            { "scarecrow", new Entry { pivotY = 0.142f, footW = 0.701f, aspect = 1.165f, skirt = true, lights = new Light[] {  }, grounds = new string[] {  } } },
            { "hay_barrel", new Entry { pivotY = 0.347f, footW = 0.966f, aspect = 0.640f, skirt = true, lights = new Light[] {  }, grounds = new string[] {  } } },
            { "banner_lamp", new Entry { pivotY = 0.148f, footW = 0.696f, aspect = 1.063f, skirt = true, lights = new Light[] { new Light { at = new Vector2(0.208f, 0.552f), fire = false } }, grounds = new string[] { "snow", "ash", "slate", "sand" } } },
            { "mailbox", new Entry { pivotY = 0.196f, footW = 0.979f, aspect = 1.183f, skirt = true, lights = new Light[] {  }, grounds = new string[] {  } } },
            { "sign_leaf", new Entry { pivotY = 0.153f, footW = 0.861f, aspect = 1.324f, skirt = true, lights = new Light[] {  }, grounds = new string[] { "snow", "ash", "slate", "sand" } } },
            { "well", new Entry { pivotY = 0.185f, footW = 0.865f, aspect = 1.061f, skirt = true, lights = new Light[] {  }, grounds = new string[] { "snow" } } },
            { "mossy_rock", new Entry { pivotY = 0.244f, footW = 0.952f, aspect = 0.894f, skirt = true, lights = new Light[] {  }, grounds = new string[] { "snow", "ash", "slate", "sand" } } },
            { "barrel", new Entry { pivotY = 0.193f, footW = 0.961f, aspect = 1.168f, skirt = true, lights = new Light[] {  }, grounds = new string[] { "ash", "sand" } } },
            { "lamp_iron", new Entry { pivotY = 0.104f, footW = 0.919f, aspect = 1.985f, skirt = true, lights = new Light[] { new Light { at = new Vector2(0.792f, 0.621f), fire = false } }, grounds = new string[] { "snow", "ash", "slate", "sand" } } },
            { "arrow_sign", new Entry { pivotY = 0.115f, footW = 0.843f, aspect = 1.787f, skirt = true, lights = new Light[] {  }, grounds = new string[] {  } } },
            { "mill", new Entry { pivotY = 0.159f, footW = 0.908f, aspect = 1.309f, skirt = true, spinAt = new Vector2(0.577f, 0.712f), spinSize = 0.918f, lights = new Light[] {  }, grounds = new string[] {  } } },
            { "market", new Entry { pivotY = 0.211f, footW = 0.965f, aspect = 1.060f, skirt = true, lights = new Light[] {  }, grounds = new string[] { "sand" } } },
        };

        public static bool Has(string name) { return All.ContainsKey(name); }
    }
}
