/* generated by Assets/Editor/LandingWeb.cs from Core/MoonCalendar.cs, Core/FestivalSys.cs and Core/LandingTheme.cs — do not edit; every web build writes it again */
window.MATU_LANDING = {
  "version": 1,
  "dayMs": 86400000,
  "weekMs": 604800000,
  "weekZeroMs": 320400000,
  "openAfterMs": 432000000,
  "closeAfterMs": 604800000,
  "claimAfterMs": 691200000,
  "festivalRibbon": "L\u1ec5 h\u1ed9i L\u00e0ng M\u00e2y \u00b7 c\u00f2n ",
  "festivalName": "L\u1ec5 h\u1ed9i L\u00e0ng M\u00e2y",
  "moonName": "H\u1ed9i Tr\u0103ng R\u1eb1m",
  "moon": [
    { "year": 2026, "week": 2959, "opens": 1790010000000, "day": 1790269200000, "evening": 1790334000000, "closes": 1790528400000, "claimUntil": 1790614800000,
      "ribbon": { "before": "H\u1ed9i Tr\u0103ng R\u1eb1m \u00b7 \u0111\u00eam r\u1eb1m t\u1ed1i th\u1ee9 S\u00e1u 25/9", "today": "H\u1ed9i Tr\u0103ng R\u1eb1m \u00b7 \u0111\u00eam r\u1eb1m t\u1ed1i nay", "ram": "\u0110\u00eam r\u1eb1m! Ph\u00e1 c\u1ed7 c\u00f9ng B\u00e1c Ba", "claim": "Qu\u00e0 Trung Thu \u00b7 nh\u1eadn t\u1edbi h\u1ebft th\u1ee9 Hai" } },
    { "year": 2027, "week": 3010, "opens": 1820854800000, "day": 1820941200000, "evening": 1821006000000, "closes": 1821373200000, "claimUntil": 1821459600000,
      "ribbon": { "before": "H\u1ed9i Tr\u0103ng R\u1eb1m \u00b7 \u0111\u00eam r\u1eb1m t\u1ed1i th\u1ee9 T\u01b0 15/9", "today": "H\u1ed9i Tr\u0103ng R\u1eb1m \u00b7 \u0111\u00eam r\u1eb1m t\u1ed1i nay", "ram": "\u0110\u00eam r\u1eb1m! Ph\u00e1 c\u1ed7 c\u00f9ng B\u00e1c Ba", "claim": "Qu\u00e0 Trung Thu \u00b7 nh\u1eadn t\u1edbi h\u1ebft th\u1ee9 Hai" } },
    { "year": 2028, "week": 3065, "opens": 1854118800000, "day": 1854118800000, "evening": 1854183600000, "closes": 1854637200000, "claimUntil": 1854723600000,
      "ribbon": { "before": "H\u1ed9i Tr\u0103ng R\u1eb1m \u00b7 \u0111\u00eam r\u1eb1m t\u1ed1i nay", "today": "H\u1ed9i Tr\u0103ng R\u1eb1m \u00b7 \u0111\u00eam r\u1eb1m t\u1ed1i nay", "ram": "\u0110\u00eam r\u1eb1m! Ph\u00e1 c\u1ed7 c\u00f9ng B\u00e1c Ba", "claim": "Qu\u00e0 Trung Thu \u00b7 nh\u1eadn t\u1edbi h\u1ebft th\u1ee9 Hai" } },
    { "year": 2029, "week": 3115, "opens": 1884358800000, "day": 1884704400000, "evening": 1884769200000, "closes": 1884877200000, "claimUntil": 1884963600000,
      "ribbon": { "before": "H\u1ed9i Tr\u0103ng R\u1eb1m \u00b7 \u0111\u00eam r\u1eb1m t\u1ed1i th\u1ee9 B\u1ea3y 22/9", "today": "H\u1ed9i Tr\u0103ng R\u1eb1m \u00b7 \u0111\u00eam r\u1eb1m t\u1ed1i nay", "ram": "\u0110\u00eam r\u1eb1m! Ph\u00e1 c\u1ed7 c\u00f9ng B\u00e1c Ba", "claim": "Qu\u00e0 Trung Thu \u00b7 nh\u1eadn t\u1edbi h\u1ebft th\u1ee9 Hai" } },
    { "year": 2030, "week": 3166, "opens": 1915203600000, "day": 1915376400000, "evening": 1915441200000, "closes": 1915722000000, "claimUntil": 1915808400000,
      "ribbon": { "before": "H\u1ed9i Tr\u0103ng R\u1eb1m \u00b7 \u0111\u00eam r\u1eb1m t\u1ed1i th\u1ee9 N\u0103m 12/9", "today": "H\u1ed9i Tr\u0103ng R\u1eb1m \u00b7 \u0111\u00eam r\u1eb1m t\u1ed1i nay", "ram": "\u0110\u00eam r\u1eb1m! Ph\u00e1 c\u1ed7 c\u00f9ng B\u00e1c Ba", "claim": "Qu\u00e0 Trung Thu \u00b7 nh\u1eadn t\u1edbi h\u1ebft th\u1ee9 Hai" } },
    { "year": 2031, "week": 3221, "opens": 1948467600000, "day": 1948554000000, "evening": 1948618800000, "closes": 1948986000000, "claimUntil": 1949072400000,
      "ribbon": { "before": "H\u1ed9i Tr\u0103ng R\u1eb1m \u00b7 \u0111\u00eam r\u1eb1m t\u1ed1i th\u1ee9 T\u01b0 1/10", "today": "H\u1ed9i Tr\u0103ng R\u1eb1m \u00b7 \u0111\u00eam r\u1eb1m t\u1ed1i nay", "ram": "\u0110\u00eam r\u1eb1m! Ph\u00e1 c\u1ed7 c\u00f9ng B\u00e1c Ba", "claim": "Qu\u00e0 Trung Thu \u00b7 nh\u1eadn t\u1edbi h\u1ebft th\u1ee9 Hai" } },
    { "year": 2032, "week": 3271, "opens": 1978707600000, "day": 1979139600000, "evening": 1979204400000, "closes": 1979226000000, "claimUntil": 1979312400000,
      "ribbon": { "before": "H\u1ed9i Tr\u0103ng R\u1eb1m \u00b7 \u0111\u00eam r\u1eb1m t\u1ed1i Ch\u1ee7 nh\u1eadt 19/9", "today": "H\u1ed9i Tr\u0103ng R\u1eb1m \u00b7 \u0111\u00eam r\u1eb1m t\u1ed1i nay", "ram": "\u0110\u00eam r\u1eb1m! Ph\u00e1 c\u1ed7 c\u00f9ng B\u00e1c Ba", "claim": "Qu\u00e0 Trung Thu \u00b7 nh\u1eadn t\u1edbi h\u1ebft th\u1ee9 Hai" } },
    { "year": 2033, "week": 3322, "opens": 2009552400000, "day": 2009725200000, "evening": 2009790000000, "closes": 2010070800000, "claimUntil": 2010157200000,
      "ribbon": { "before": "H\u1ed9i Tr\u0103ng R\u1eb1m \u00b7 \u0111\u00eam r\u1eb1m t\u1ed1i th\u1ee9 N\u0103m 8/9", "today": "H\u1ed9i Tr\u0103ng R\u1eb1m \u00b7 \u0111\u00eam r\u1eb1m t\u1ed1i nay", "ram": "\u0110\u00eam r\u1eb1m! Ph\u00e1 c\u1ed7 c\u00f9ng B\u00e1c Ba", "claim": "Qu\u00e0 Trung Thu \u00b7 nh\u1eadn t\u1edbi h\u1ebft th\u1ee9 Hai" } },
    { "year": 2034, "week": 3377, "opens": 2042816400000, "day": 2042816400000, "evening": 2042881200000, "closes": 2043334800000, "claimUntil": 2043421200000,
      "ribbon": { "before": "H\u1ed9i Tr\u0103ng R\u1eb1m \u00b7 \u0111\u00eam r\u1eb1m t\u1ed1i nay", "today": "H\u1ed9i Tr\u0103ng R\u1eb1m \u00b7 \u0111\u00eam r\u1eb1m t\u1ed1i nay", "ram": "\u0110\u00eam r\u1eb1m! Ph\u00e1 c\u1ed7 c\u00f9ng B\u00e1c Ba", "claim": "Qu\u00e0 Trung Thu \u00b7 nh\u1eadn t\u1edbi h\u1ebft th\u1ee9 Hai" } },
    { "year": 2035, "week": 3427, "opens": 2073056400000, "day": 2073488400000, "evening": 2073553200000, "closes": 2073574800000, "claimUntil": 2073661200000,
      "ribbon": { "before": "H\u1ed9i Tr\u0103ng R\u1eb1m \u00b7 \u0111\u00eam r\u1eb1m t\u1ed1i Ch\u1ee7 nh\u1eadt 16/9", "today": "H\u1ed9i Tr\u0103ng R\u1eb1m \u00b7 \u0111\u00eam r\u1eb1m t\u1ed1i nay", "ram": "\u0110\u00eam r\u1eb1m! Ph\u00e1 c\u1ed7 c\u00f9ng B\u00e1c Ba", "claim": "Qu\u00e0 Trung Thu \u00b7 nh\u1eadn t\u1edbi h\u1ebft th\u1ee9 Hai" } },
    { "year": 2036, "week": 3482, "opens": 2106320400000, "day": 2106666000000, "evening": 2106730800000, "closes": 2106838800000, "claimUntil": 2106925200000,
      "ribbon": { "before": "H\u1ed9i Tr\u0103ng R\u1eb1m \u00b7 \u0111\u00eam r\u1eb1m t\u1ed1i th\u1ee9 B\u1ea3y 4/10", "today": "H\u1ed9i Tr\u0103ng R\u1eb1m \u00b7 \u0111\u00eam r\u1eb1m t\u1ed1i nay", "ram": "\u0110\u00eam r\u1eb1m! Ph\u00e1 c\u1ed7 c\u00f9ng B\u00e1c Ba", "claim": "Qu\u00e0 Trung Thu \u00b7 nh\u1eadn t\u1edbi h\u1ebft th\u1ee9 Hai" } },
    { "year": 2037, "week": 3533, "opens": 2137165200000, "day": 2137338000000, "evening": 2137402800000, "closes": 2137683600000, "claimUntil": 2137770000000,
      "ribbon": { "before": "H\u1ed9i Tr\u0103ng R\u1eb1m \u00b7 \u0111\u00eam r\u1eb1m t\u1ed1i th\u1ee9 N\u0103m 24/9", "today": "H\u1ed9i Tr\u0103ng R\u1eb1m \u00b7 \u0111\u00eam r\u1eb1m t\u1ed1i nay", "ram": "\u0110\u00eam r\u1eb1m! Ph\u00e1 c\u1ed7 c\u00f9ng B\u00e1c Ba", "claim": "Qu\u00e0 Trung Thu \u00b7 nh\u1eadn t\u1edbi h\u1ebft th\u1ee9 Hai" } }
  ],
  "colors": {
    "moon": { "skyTop": "#0B1433", "skyMid": "#172556", "skyLow": "#2A3E73", "skyHor": "#3F5A8E", "cloud": "#8C9FD2", "glow": "#E2D3B6", "ribbonTop": "#E4553F", "ribbonBottom": "#B32A22", "ribbonLip": "#6E1812", "ribbonInk": "#FFF4DC", "ribbonLine": "#6A1510" },
    "festival": { "ribbonTop": "#5CC46F", "ribbonBottom": "#2F8F4C", "ribbonLip": "#1C6A35", "ribbonInk": "#FFFFFF", "ribbonLine": "#1C5E33" }
  }
};
